import type { PresetConfig } from '../types/plasma';

export const PLASMA_PRESETS: PresetConfig[] = [
  {
    id: 'tokamak',
    name: 'Tokamak Fusion Reactor',
    description: 'Magnetic confinement fusion plasma exhibiting toroidal helical magnetic flux surfaces and internal kink mode oscillations.',
    category: 'Fusion',
    icon: 'Atom',
    params: {
      particleCount: 65000,
      magneticFieldType: 'tokamak',
      magneticFieldStrength: 4.5,
      temperature: 15000,
      ionizationRate: 0.95,
      pressure: 0.2,
      turbulence: 0.25,
      kinkInstability: 0.35,
      sausageInstability: 0.15,
      branchProbability: 0.1,
      filamentPersistence: 0.4,
      glowIntensity: 1.4,
      simulationSpeed: 1.0,
      collisionRate: 0.1,
      energyLoss: 0.02,
    },
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare & Corona',
    description: 'High-energy coronal loops driven by magnetic reconnection bursts releasing kinetic jets into space.',
    category: 'Astrophysical',
    icon: 'Sun',
    params: {
      particleCount: 75000,
      magneticFieldType: 'dipole',
      magneticFieldStrength: 3.8,
      temperature: 25000,
      ionizationRate: 1.0,
      pressure: 0.05,
      turbulence: 0.6,
      kinkInstability: 0.4,
      sausageInstability: 0.3,
      branchProbability: 0.4,
      filamentPersistence: 0.6,
      glowIntensity: 1.8,
      simulationSpeed: 1.2,
      collisionRate: 0.05,
      energyLoss: 0.01,
    },
    magnets: [
      { position: { x: 0, y: -6, z: 0 }, dipoleMoment: { x: 0, y: 1, z: 0 }, strength: 5.0 },
    ],
  },
  {
    id: 'z-pinch',
    name: 'Z-Pinch Discharge',
    description: 'Ultra-dense longitudinal electric discharge creating strong azimuthal B-field and severe sausage (m=0) instabilities.',
    category: 'Laboratory',
    icon: 'Zap',
    params: {
      particleCount: 60000,
      magneticFieldType: 'uniform',
      magneticFieldStrength: 1.2,
      electricFieldStrength: 4.0,
      voltage: 800,
      temperature: 8000,
      ionizationRate: 0.85,
      pressure: 1.5,
      turbulence: 0.4,
      sausageInstability: 0.75,
      kinkInstability: 0.2,
      branchProbability: 0.7,
      filamentPersistence: 0.8,
      glowIntensity: 2.0,
      simulationSpeed: 0.9,
    },
    electrodes: [
      { position: { x: 0, y: -8, z: 0 }, charge: 1, voltage: 600, radius: 1.5 },
      { position: { x: 0, y: 8, z: 0 }, charge: -1, voltage: -600, radius: 1.5 },
    ],
  },
  {
    id: 'aurora',
    name: 'Aurora Borealis',
    description: 'Energetic magnetospheric electron cascade spiraling down polar dipole magnetic field lines into upper atmosphere.',
    category: 'Atmospheric',
    icon: 'Sparkles',
    params: {
      particleCount: 70000,
      magneticFieldType: 'dipole',
      magneticFieldStrength: 5.0,
      temperature: 3000,
      ionizationRate: 0.6,
      pressure: 0.4,
      turbulence: 0.15,
      kinkInstability: 0.1,
      sausageInstability: 0.05,
      branchProbability: 0.2,
      filamentPersistence: 0.5,
      glowIntensity: 1.3,
      simulationSpeed: 0.8,
    },
  },
  {
    id: 'corona-discharge',
    name: 'Corona Electric Arcs',
    description: 'High-voltage dielectric breakdown generating multi-branching neon arcs between electrodes.',
    category: 'Laboratory',
    icon: 'Activity',
    params: {
      particleCount: 50000,
      magneticFieldType: 'none',
      electricFieldStrength: 5.0,
      voltage: 1200,
      temperature: 4500,
      ionizationRate: 0.9,
      pressure: 2.0,
      turbulence: 0.3,
      branchProbability: 0.9,
      filamentPersistence: 0.85,
      glowIntensity: 2.2,
      simulationSpeed: 1.0,
    },
    electrodes: [
      { position: { x: -6, y: 0, z: 0 }, charge: 1, voltage: 800, radius: 1.2 },
      { position: { x: 6, y: 0, z: 0 }, charge: -1, voltage: -800, radius: 1.2 },
    ],
  },
  {
    id: 'glow-discharge',
    name: 'Plasma Globe',
    description: 'Low-pressure central RF electrode discharge emitting mobile glowing plasma filaments against dielectric spherical glass.',
    category: 'Laboratory',
    icon: 'Globe',
    params: {
      particleCount: 45000,
      magneticFieldType: 'rotating',
      magneticFieldStrength: 1.5,
      electricFieldStrength: 3.5,
      voltage: 500,
      temperature: 2500,
      ionizationRate: 0.7,
      pressure: 1.0,
      turbulence: 0.2,
      branchProbability: 0.65,
      filamentPersistence: 0.7,
      glowIntensity: 1.6,
    },
    electrodes: [
      { position: { x: 0, y: 0, z: 0 }, charge: 1, voltage: 500, radius: 1.5 },
    ],
  },
  {
    id: 'magnetosphere',
    name: 'Magnetosphere Storm',
    description: 'Planetary magnetosphere boundary under solar wind pressure, forming magnetotail current sheets and reconnection.',
    category: 'Astrophysical',
    icon: 'Shield',
    params: {
      particleCount: 80000,
      magneticFieldType: 'dipole',
      magneticFieldStrength: 4.2,
      temperature: 12000,
      ionizationRate: 0.9,
      pressure: 0.1,
      turbulence: 0.5,
      kinkInstability: 0.3,
      branchProbability: 0.3,
      glowIntensity: 1.5,
    },
  },
  {
    id: 'nebula-plasma',
    name: 'Cosmic Nebula Plasma',
    description: 'Turbulent cosmic cloud with self-organizing ionized gas filaments and magnetic turbulence.',
    category: 'Astrophysical',
    icon: 'Cloud',
    params: {
      particleCount: 90000,
      magneticFieldType: 'rotating',
      magneticFieldStrength: 2.2,
      temperature: 6000,
      ionizationRate: 0.8,
      pressure: 0.02,
      turbulence: 0.7,
      branchProbability: 0.25,
      glowIntensity: 1.7,
    },
  },
];
